name: Typecheck

on:
  push:
    branches: ["*"]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: find . -type f -name "package.json" -not -path "./node_modules/*" -execdir npm install \;
      - name: Typecheck
        run: npm run typecheck
